import express from 'express';
import { authenticate } from '../middleware/auth.middleware.js';
import { apiLimiter } from '../middleware/rateLimiter.js';
import geminiService from '../services/gemini.service.js';
import { logger } from '../utils/logger.js';

const router = express.Router();

// GET /api/ai-study-buddy/status - Gemini availability/status
router.get('/status', async (req, res) => {
  try {
    res.json({
      success: true,
      data: {
        available: !!geminiService.isAvailable,
        model: process.env.GEMINI_MODEL || null,
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// POST /api/ai-study-buddy/generate - Generate quiz from conversation
router.post('/generate', authenticate, apiLimiter, async (req, res, next) => {
  try {
    const { topics, text } = req.body;

    if (!topics && !text) {
      return res.status(400).json({ success: false, error: 'Topics or text required' });
    }

    // Combine topics and text
    let inputText = '';
    if (topics && Array.isArray(topics)) {
      inputText = `Topics: ${topics.join(', ')}\n\n`;
    } else if (topics && typeof topics === 'string') {
      inputText = `Topics: ${topics}\n\n`;
    }
    
    if (text) {
      inputText += `Content:\n${text.substring(0, 10000)}`; // Limit to 10k chars
    }

    if (!inputText) {
      return res.status(400).json({ success: false, error: 'No input provided' });
    }

    // Generate 3-10 questions based on input
    const maxQuestions = Math.min(10, Math.max(3, Math.floor(inputText.length / 500)));
    
    const questions = await geminiService.generateMCQsFromText(inputText, maxQuestions);

    // Return quiz-like structure for immediate use
    res.json({
      success: true,
      data: {
        questions,
        title: `AI Generated Quiz: ${topics || 'Custom Quiz'}`,
        description: 'Generated by AI Study Buddy',
        totalQuestions: questions.length,
      },
    });
  } catch (error) {
    logger.error('AI Study Buddy error:', error);
    next(error);
  }
});

export default router;

